train:
    lr: 0.03
    max_epochs: 30
    score_data: true
    model: 'multic' # [multic, ncf]
    early_stopping: true
    mixer_lambda: 0.5
    kt_only: false
    num_d: 4
    num_opt: 5
    weight_decay: false
    weight_decaying_lambda: 0.001
    random_seed: 1
    hidden_dim: 4
    num_layers: 3
    out_dim: 1
ncf:
    num_d: 1
    hidden_dim: 1
    num_layers: 3
    out_dim: 1
early_stopping:
    patience: 10
evaluate:
    batch_size: 74000
    epochs: 10
score:
    pre_transform_opt: "Recent"
    loss: bce
    split:
        - 0.75
        - 0.25
factor: 1
gpus: '1'
batch_size: 74000
epochs: 200
num_workers: 16
num_q: 185
split: true
type: 'mix' #['sp', 'mix']
version: 2
data:
    dataset_type: "toeic"
    drop_seed: 0
    drop_ratio: 0 
    demo: false
    version: '25' # ["10", "25", "50"]
    root: "/root/data/toeic_data"
    mapper: "/root/data/toeic_data/mappers"
    split:
        mix:
            - 0.1
            - 0.1